"""CineSignal ETL — parse, clean, derive, and report (PRD FR-1).

Turns the raw TMDB 5000 CSVs into a single clean Parquet dataset with a documented
schema, and emits a data-quality report of what was kept/dropped and why.

Design notes
------------
* Transform functions are **pure** (row/value in → value out) so they are unit-tested
  without needing the raw dataset in CI (PRD §13 Testability).
* The pipeline is **deterministic and re-runnable from one command** (AC-1.5):
  `python -m pipeline.etl`.
* Every non-obvious cleaning choice is logged into the DataQualityReport and mirrored
  in docs/decisions.md (AC-1.6, PRD §15).
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field

import numpy as np
import pandas as pd

from pipeline import CLEAN_PARQUET, DATA_PROCESSED, REPORTS
from pipeline.acquire import resolve

logger = logging.getLogger("cinesignal.etl")

# --- Documented thresholds (no magic numbers; see docs/methodology.md) --------

# Budget tiers (nominal USD). Bands chosen to reflect industry-recognised buckets.
BUDGET_TIERS = [
    ("micro", 0, 1_000_000),          # < $1M
    ("low", 1_000_000, 10_000_000),   # $1M–$10M
    ("mid", 10_000_000, 50_000_000),  # $10M–$50M
    ("high", 50_000_000, 100_000_000),  # $50M–$100M
    ("tentpole", 100_000_000, np.inf),  # ≥ $100M
]

# Below this, a *non-zero* financial value is almost certainly a data-entry error
# (e.g. a $12 "budget") rather than a real micro-budget. Flagged, not silently kept.
MIN_PLAUSIBLE_FINANCIAL = 1_000  # USD

# Plausible release-year window for this corpus (TMDB 5000 spans ~1916–2017).
MIN_YEAR, MAX_YEAR = 1900, 2020

N_TOP_CAST = 3  # lead actors retained for the Talent Impact view (FR-9)


# --- Data-quality report ------------------------------------------------------


@dataclass
class DataQualityReport:
    """Accumulates row-level bookkeeping so cleaning is transparent (AC-1.6)."""

    steps: list[tuple[str, int, str]] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    def record(self, step: str, rows: int, detail: str = "") -> None:
        logger.info("%s → %d rows %s", step, rows, f"({detail})" if detail else "")
        self.steps.append((step, rows, detail))

    def note(self, msg: str) -> None:
        logger.info(msg)
        self.notes.append(msg)

    def to_markdown(self) -> str:
        lines = [
            "# CineSignal — Data-Quality Report",
            "",
            "_Auto-generated by `pipeline/etl.py` (PRD FR-1, AC-1.6). Do not edit by hand._",
            "",
            "## Row accounting",
            "",
            "| Step | Rows | Detail |",
            "|---|---:|---|",
        ]
        lines += [f"| {s} | {r:,} | {d} |" for s, r, d in self.steps]
        if self.notes:
            lines += ["", "## Notes & flags", ""]
            lines += [f"- {n}" for n in self.notes]
        lines.append("")
        return "\n".join(lines)


# --- Pure transforms (unit-tested in tests/test_transforms.py) ----------------


def parse_json_names(value: object, key: str = "name") -> list[str]:
    """Parse a TMDB JSON-array cell (e.g. genres) into a list of names.

    Robust to NaN, empty strings, and already-parsed lists. Returns [] on anything
    unparseable rather than raising, so one bad cell never aborts the pipeline.
    """
    if isinstance(value, list):
        items = value
    elif isinstance(value, str) and value.strip():
        try:
            items = json.loads(value)
        except (json.JSONDecodeError, ValueError):
            return []
    else:
        return []
    return [d[key] for d in items if isinstance(d, dict) and key in d]


def extract_director(crew_value: object) -> str | None:
    """Return the first Director's name from a TMDB crew JSON cell, else None."""
    if isinstance(crew_value, str) and crew_value.strip():
        try:
            crew = json.loads(crew_value)
        except (json.JSONDecodeError, ValueError):
            return None
    elif isinstance(crew_value, list):
        crew = crew_value
    else:
        return None
    for member in crew:
        if isinstance(member, dict) and member.get("job") == "Director":
            return member.get("name")
    return None


def extract_top_cast(cast_value: object, n: int = N_TOP_CAST) -> list[str]:
    """Return up to n billed lead actor names (TMDB cast is ordered by billing)."""
    names = parse_json_names(cast_value, key="name")
    return names[:n]


def assign_budget_tier(budget: float) -> str | None:
    """Map a budget to a documented tier, or None if budget is missing/zero."""
    if budget is None or not np.isfinite(budget) or budget <= 0:
        return None
    for name, lo, hi in BUDGET_TIERS:
        if lo <= budget < hi:
            return name
    return None


def compute_roi(revenue: float, budget: float) -> float:
    """ROI = (revenue − budget) / budget. Caller guarantees budget > 0."""
    return (revenue - budget) / budget


# --- DataFrame-level pipeline -------------------------------------------------


def load_raw() -> tuple[pd.DataFrame, pd.DataFrame]:
    acq = resolve()
    movies = pd.read_csv(acq.movies_path)
    credits = pd.read_csv(acq.credits_path)
    return movies, credits


def clean(
    movies: pd.DataFrame, credits: pd.DataFrame, report: DataQualityReport | None = None
) -> tuple[pd.DataFrame, DataQualityReport]:
    """Full clean: join → parse → normalise → flag → derive. Returns (clean_df, report)."""
    report = report or DataQualityReport()
    report.record("raw movies", len(movies))
    report.record("raw credits", len(credits))

    # --- Join credits onto movies (reproduce the join ourselves; PRD §12.1) ---
    # credits.movie_id ↔ movies.id. credits also has a `title` we drop to avoid clash.
    credits = credits.rename(columns={"movie_id": "id"})[["id", "cast", "crew"]]
    df = movies.merge(credits, on="id", how="left")
    report.record("after join", len(df), "movies ⋈ credits on id")

    # --- Deduplicate on stable id (TMDB 5000 has known duplicate rows) ---------
    before = len(df)
    df = df.drop_duplicates(subset="id", keep="first")
    if before != len(df):
        report.note(f"Dropped {before - len(df)} duplicate movie id(s).")
    report.record("after dedup", len(df), "on id")

    # --- Normalise identity fields --------------------------------------------
    df["title"] = df["title"].astype("string").str.strip()
    dup_titles = df["title"].duplicated(keep=False).sum()
    if dup_titles:
        report.note(
            f"{dup_titles} rows share a title with another film → kept, "
            "disambiguated by `id` (Movie Deep-Dive must handle collisions, AC-6.1)."
        )

    # --- Parse nested JSON encodings (AC-1.2) ---------------------------------
    df["genres"] = df["genres"].apply(parse_json_names)
    df["keywords"] = df["keywords"].apply(parse_json_names)
    df["production_countries"] = df["production_countries"].apply(parse_json_names)
    df["production_companies"] = df["production_companies"].apply(parse_json_names)
    df["director"] = df["crew"].apply(extract_director)
    df["cast_top"] = df["cast"].apply(extract_top_cast)
    df = df.drop(columns=["cast", "crew"])

    # --- Dates → year / month (AC-1.4) ----------------------------------------
    df["release_date"] = pd.to_datetime(df["release_date"], errors="coerce")
    df["release_year"] = df["release_date"].dt.year
    df["release_month"] = df["release_date"].dt.month
    bad_year = df["release_year"].notna() & ~df["release_year"].between(MIN_YEAR, MAX_YEAR)
    if bad_year.any():
        report.note(f"Flagged {int(bad_year.sum())} row(s) with implausible release year.")
    missing_date = df["release_date"].isna().sum()
    if missing_date:
        report.note(f"{missing_date} row(s) have no parseable release_date.")

    # --- Financials: zeros-as-nulls + implausible-value flags (AC-1.3) --------
    for col in ("budget", "revenue"):
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # A zero means "unknown" in TMDB, not "free" → treat as missing for ROI.
    zero_budget = (df["budget"] == 0).sum()
    zero_revenue = (df["revenue"] == 0).sum()
    report.note(f"budget == 0 (treated as missing): {zero_budget} rows.")
    report.note(f"revenue == 0 (treated as missing): {zero_revenue} rows.")

    df["budget_valid"] = df["budget"] > 0
    df["revenue_valid"] = df["revenue"] > 0

    implausible = (
        (df["budget_valid"] & (df["budget"] < MIN_PLAUSIBLE_FINANCIAL))
        | (df["revenue_valid"] & (df["revenue"] < MIN_PLAUSIBLE_FINANCIAL))
    )
    if implausible.any():
        report.note(
            f"Flagged {int(implausible.sum())} row(s) with non-zero but implausibly "
            f"small (<${MIN_PLAUSIBLE_FINANCIAL:,}) financials → excluded from ROI."
        )
    df["financials_valid"] = df["budget_valid"] & df["revenue_valid"] & ~implausible

    # --- Derived fields (§12.3) — ROI only where financials are valid ----------
    df["profit"] = np.where(df["financials_valid"], df["revenue"] - df["budget"], np.nan)
    df["roi"] = np.where(
        df["financials_valid"], (df["revenue"] - df["budget"]) / df["budget"], np.nan
    )
    df["is_profitable"] = np.where(df["financials_valid"], df["profit"] > 0, pd.NA)
    df["budget_tier"] = df["budget"].apply(assign_budget_tier)

    n_roi = int(df["financials_valid"].sum())
    report.record(
        "ROI-computable rows", n_roi, f"{n_roi / len(df):.0%} of films have valid budget+revenue"
    )

    # --- Reception: vote_count as a reliability signal (kept, not filtered) ----
    df["vote_average"] = pd.to_numeric(df["vote_average"], errors="coerce")
    df["vote_count"] = pd.to_numeric(df["vote_count"], errors="coerce").fillna(0).astype(int)
    report.note(
        "TMDB provides only an audience score (vote_average); no critic score. "
        "Critics-vs-Audience (FR-5) needs an IMDB `title.ratings` enrichment on imdb_id."
    )

    # --- Provenance for the scope/bias caveat (AC-7.1) -------------------------
    df["original_language"] = df["original_language"].astype("string")
    usa = df["production_countries"].apply(
        lambda cs: "United States of America" in cs if isinstance(cs, list) else False
    )
    report.note(
        f"US-produced films: {usa.mean():.0%} — corpus is US/English-skewed; "
        "state this scope limit on the Methodology page (AC-7.1)."
    )

    # --- Final schema selection + deterministic ordering (AC-1.5) --------------
    keep = [
        "id", "title", "original_title", "original_language",
        "budget", "revenue", "profit", "roi", "is_profitable", "financials_valid",
        "budget_valid", "revenue_valid", "budget_tier",
        "vote_average", "vote_count", "popularity", "runtime",
        "genres", "keywords", "production_countries", "production_companies",
        "director", "cast_top",
        "release_date", "release_year", "release_month",
    ]
    df = df[[c for c in keep if c in df.columns]].sort_values("id").reset_index(drop=True)
    report.record("clean dataset", len(df), f"{df.shape[1]} columns")
    return df, report


def run() -> pd.DataFrame:
    """End-to-end: load → clean → write Parquet + data-quality report. Returns clean df."""
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    movies, credits = load_raw()
    df, report = clean(movies, credits)

    DATA_PROCESSED.mkdir(parents=True, exist_ok=True)
    REPORTS.mkdir(parents=True, exist_ok=True)
    df.to_parquet(CLEAN_PARQUET, index=False)
    (REPORTS / "data_quality.md").write_text(report.to_markdown())

    logger.info("✓ Wrote %s (%d rows)", CLEAN_PARQUET, len(df))
    logger.info("✓ Wrote %s", REPORTS / "data_quality.md")
    return df


def main() -> int:
    try:
        run()
    except FileNotFoundError as exc:
        print(str(exc))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
