"""Methodology & Data-Quality page (FR-7) — a first-class feature, not fine print.

Surfaces, in-app, the same documents a reviewer would read: the methodology write-up,
the auto-generated data-quality report, and the live data dictionary. AC-7.1–7.4.
"""
from __future__ import annotations

import streamlit as st

from app.components import ui
from app.components.data import load_data
from pipeline import ROOT

DOCS = ROOT / "docs"
REPORTS = ROOT / "reports"


def _read(path) -> str | None:
    return path.read_text() if path.exists() else None


def render() -> None:
    st.title("📐 Methodology & Data")
    ui.headline(
        "Every number in CineSignal traces back to one reproducible pipeline — "
        "here is exactly how the data was cleaned and how each metric is defined."
    )

    df = load_data()
    valid = df.financials_valid.sum()
    tabs = st.tabs(["Methodology", "Data-quality report", "Data dictionary", "Live snapshot"])

    with tabs[0]:
        text = _read(DOCS / "methodology.md")
        st.markdown(text if text else "_methodology.md not found_")
        with st.expander("Decisions log (ADR-style rationale)"):
            st.markdown(_read(DOCS / "decisions.md") or "_decisions.md not found_")

    with tabs[1]:
        st.caption("Auto-generated by `pipeline/etl.py` each run (AC-1.6).")
        st.markdown(_read(REPORTS / "data_quality.md") or "_run the pipeline to generate this_")

    with tabs[2]:
        st.markdown(_read(DOCS / "data_dictionary.md") or "_data_dictionary.md not found_")

    with tabs[3]:
        st.caption("Computed live from the loaded dataset — a sanity check on the docs above.")
        c1, c2, c3 = st.columns(3)
        c1.metric("Films", f"{len(df):,}")
        c2.metric("ROI-computable", f"{valid:,}", f"{valid / len(df):.0%} of corpus")
        c3.metric("Columns", f"{df.shape[1]}")

    ui.footer()
